// ============================================================================
//  PORTS (contracts / interfaces) of the core — the system's "sockets"
// ============================================================================
//
//  WHAT IS A "PORT"?
//  It's a CONTRACT: it says WHAT a piece must do, without saying HOW. E.g. the
//  `EmbedderPort` says "I take texts and return vectors" — but does NOT say whether
//  that's done by OpenAI or a local model. The ADAPTERS (in src/adapters/) decide
//  the "how" and "plug into" these sockets.
//
//  WHY DOES THIS MATTER? (Hexagonal Architecture + the "D" of SOLID)
//  The core depends only on these interfaces (abstractions), never on a concrete
//  technology. Practical result:
//    • swapping the LLM or the database = swapping 1 adapter, without touching the logic;
//    • testing the core with "doubles" (fakes) that implement the same contract.
//  This is Dependency Inversion — the "D" of SOLID.
//
//  WHY DO THE METHODS RETURN Promise?
//  Because in Node, reading a file, generating an embedding and calling the LLM are
//  ASYNCHRONOUS operations (they wait on disk/network). `Promise<T>` = "I'll hand
//  you a T, but in a moment". The caller uses `await` to wait for the result.
// ============================================================================

import type {
  ChatMessage,
  ChatResult,
  Chunk,
  Document,
  ProfileSummary,
  RetrievedContext,
  ToolSpec,
  Turn,
} from './models.ts';

/** Reads a file (PDF/MD/txt) and returns a Document (text + metadata). */
export interface DocumentParserPort {
  parse(path: string): Promise<Document>;
}

/** Splits a Document into several Chunks. (pure/synchronous → easy to test) */
export interface ChunkerPort {
  chunk(document: Document): Chunk[];
}

/** Turns texts into vectors (embeddings) — the numeric "fingerprint" of the text. */
export interface EmbedderPort {
  embed(texts: string[]): Promise<number[][]>; // 1 vector of numbers per text
}

/** Stores the vectorized chunks and searches for the ones most similar to the question. */
export interface VectorStorePort {
  add(chunks: Chunk[], embeddings: number[][]): Promise<void>; // index (store)
  search(queryEmbedding: number[], k: number): Promise<RetrievedContext>; // fetch top-k
}

/** Takes a prompt (rules + question) and returns the text generated by the model. */
export interface LLMPort {
  generate(systemPrompt: string, userPrompt: string): Promise<string>;
}

/**
 * Stores and retrieves the conversation history (the mentor's MEMORY). Thanks to
 * it the dialogue has continuity: the mentor remembers what was already said.
 * Being a PORT, it can live in memory (tests) or in Mongo (persistent).
 */
export interface MemoryPort {
  append(sessionId: string, turn: Turn): Promise<void>; // add a turn
  history(sessionId: string, limit?: number): Promise<Turn[]>; // latest turns (in order)
}

/**
 * Records and summarizes the student's LEARNING PROFILE: what they've asked and
 * which sources were touched. Unlike memory (which stores the dialogue turn by
 * turn for continuity), the profile is an AGGREGATE view — it tells "what the
 * student has been studying / where they search most". Being a PORT, it can live
 * in memory (tests) or in Mongo (persistent), without touching the core.
 */
export interface ProfilePort {
  record(studentId: string, question: string, sources: string[]): Promise<void>; // records 1 study
  summary(studentId: string): Promise<ProfileSummary>; // returns the aggregate summary
}

/**
 * LLM with TOOL-CALLING support (Step 11 — the agent). It's a SEPARATE contract
 * from LLMPort on purpose: the RAG only needs `generate(system, user)`, so it makes
 * no sense to force it to know about tools (that's the "I" of SOLID — interface
 * segregation). Whoever needs autonomy uses this richer port.
 *
 * It takes the dialogue (messages) + the list of available tools; it returns EITHER
 * a final text OR requests to call tools (the model decides).
 */
export interface ToolCallingLLMPort {
  chat(messages: ChatMessage[], tools: ToolSpec[]): Promise<ChatResult>;
}

/**
 * The agent's source of TOOLS. In our case, the concrete adapter wraps an MCP
 * CLIENT: the agent "consumes the MCP" we built in Step 9 — it lists the tools
 * (`ask`, `my_progress`) and executes them over the protocol. Being a PORT, the
 * agent doesn't know it's MCP underneath → it can be tested with a double.
 */
export interface AgentToolsPort {
  listTools(): Promise<ToolSpec[]>; // which tools exist (for the model to choose)
  callTool(name: string, argumentsJson: string): Promise<string>; // executes and returns the text
}

/**
 * The evaluation "judge" (Step 13, optional): gives a FAITHFULNESS score — how much
 * the answer relies on the context/sources, without making things up (0 = made up,
 * 1 = faithful). It's "LLM-as-judge": one model evaluates another's output. It sits
 * behind a PORT because it's OPTIONAL and expensive (uses quota); tests use a fake judge.
 */
export interface JudgePort {
  faithfulness(question: string, answer: string, context: string): Promise<number>; // 0 to 1
}
