// ============================================================================
//  SIMILARITY — the math behind the RAG's "search by meaning"
// ============================================================================
//
//  WHAT IS AN EMBEDDING (for context)?
//  An embedding is a list of numbers (a "vector") that represents the MEANING of a
//  text. Similar texts produce similar vectors (they point in nearby directions in
//  space). That's how the RAG finds the right snippet even when the words differ.
//
//  HOW DO WE MEASURE "SIMILAR"? Cosine similarity.
//  Picture each vector as an ARROW from the origin. Cosine similarity measures the
//  ANGLE between two arrows (ignoring their length):
//    • arrows in the SAME direction  → cosine = 1   (very similar)
//    • PERPENDICULAR arrows          → cosine = 0   (unrelated)
//    • OPPOSITE arrows               → cosine = -1  (contrary)
//
//  Formula:  cos(a, b) = (a · b) / (‖a‖ × ‖b‖)
//    • a · b  = dot product (sum of a[i] * b[i])
//    • ‖a‖    = "length" (norm) of the vector = square root of the sum of squares
//
//  It's PURE math (no I/O), so it lives in the core and is easy to test.
// ============================================================================

/**
 * Computes the cosine similarity between two vectors.
 * Returns a number between -1 (opposite) and 1 (identical in direction).
 */
export function cosineSimilarity(a: number[], b: number[]): number {
  if (a.length !== b.length) {
    throw new Error(
      `Vectors of different sizes (${a.length} vs ${b.length}). ` +
        'This usually means they were generated by different embedding models.',
    );
  }

  let dotProduct = 0; // a · b
  let normA = 0; // ‖a‖² (we sum the squares; take the root at the end)
  let normB = 0; // ‖b‖²

  for (let i = 0; i < a.length; i++) {
    dotProduct += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }

  const denominator = Math.sqrt(normA) * Math.sqrt(normB);

  // A "zero" vector has no direction → we avoid dividing by zero.
  if (denominator === 0) return 0;

  return dotProduct / denominator;
}
